package com.example.stockquoteapp

object StockCatalog {

    val symbolsByMarket: Map<MarketCategory, List<StockReference>> = mapOf(

        MarketCategory.KOSPI to listOf(

            StockReference("005930.KS","Samsung Electronics","삼성전자"),
            StockReference("000660.KS","SK Hynix","SK하이닉스"),
            StockReference("207940.KS","Samsung Biologics","삼성바이오로직스"),
            StockReference("051910.KS","LG Chem","LG화학"),
            StockReference("006400.KS","Samsung SDI","삼성SDI"),
            StockReference("005380.KS","Hyundai Motor","현대차"),
            StockReference("012330.KS","Hyundai Mobis","현대모비스"),
            StockReference("035420.KS","NAVER","네이버"),
            StockReference("068270.KS","Celltrion","셀트리온"),
            StockReference("105560.KS","KB Financial","KB금융"),
            StockReference("055550.KS","Shinhan Financial","신한지주"),
            StockReference("086790.KS","Hana Financial","하나금융"),
            StockReference("028260.KS","Samsung C&T","삼성물산"),
            StockReference("034730.KS","SK","SK"),
            StockReference("066570.KS","LG Electronics","LG전자"),
            StockReference("032830.KS","Samsung Life","삼성생명"),
            StockReference("015760.KS","Korea Electric","한국전력"),
            StockReference("009150.KS","Samsung Electro","삼성전기"),
            StockReference("003550.KS","LG","LG"),
            StockReference("017670.KS","SK Telecom","SK텔레콤"),
            StockReference("011200.KS","HMM","HMM"),
            StockReference("018260.KS","Samsung SDS","삼성SDS"),
            StockReference("010130.KS","Korea Zinc","고려아연"),
            StockReference("096770.KS","SK Innovation","SK이노베이션"),
            StockReference("024110.KS","Industrial Bank","기업은행"),
            StockReference("011170.KS","Lotte Chemical","롯데케미칼"),
            StockReference("030200.KS","KT","KT"),
            StockReference("034020.KS","Doosan Enerbility","두산에너빌리티"),
            StockReference("000270.KS","Kia","기아"),
            StockReference("047050.KS","POSCO Holdings","POSCO홀딩스"),
            StockReference("000810.KS","Samsung Fire","삼성화재"),
            StockReference("001040.KS","CJ","CJ"),
            StockReference("004020.KS","Hyundai Steel","현대제철"),
            StockReference("010950.KS","S-Oil","S-Oil"),
            StockReference("002790.KS","AmorePacific","아모레퍼시픽"),
            StockReference("090430.KS","AmoreG","아모레G"),
            StockReference("271560.KS","Orion","오리온"),
            StockReference("036570.KS","NCSoft","엔씨소프트"),
            StockReference("161390.KS","Hankook Tire","한국타이어"),
            StockReference("000720.KS","Hyundai Engineering","현대건설"),
            StockReference("000100.KS","Yuhan","유한양행"),
            StockReference("005490.KS","POSCO","POSCO"),
            StockReference("006800.KS","Mirae Asset","미래에셋증권"),
            StockReference("008770.KS","Hotel Shilla","호텔신라"),
            StockReference("003490.KS","Korean Air","대한항공"),
            StockReference("011070.KS","LG Innotek","LG이노텍"),
            StockReference("004170.KS","Shinsegae","신세계"),
            StockReference("005940.KS","NH Investment","NH투자증권"),
            StockReference("051900.KS","LG Household","LG생활건강"),
            StockReference("000150.KS","Doosan","두산"),
            StockReference("003230.KS","Samyang","삼양"),
            StockReference("005830.KS","DB Insurance","DB손해보험"),
            StockReference("010060.KS","OCI","OCI"),
            StockReference("001450.KS","Hyundai Marine","현대해상"),
            StockReference("000880.KS","Hanwha","한화"),
            StockReference("000120.KS","CJ Logistics","CJ대한통운"),
            StockReference("042660.KS","Daewoo Ship","대우조선해양"),
            StockReference("002380.KS","KCC","KCC"),
            StockReference("003670.KS","POSCO Future","포스코퓨처엠"),
            StockReference("012450.KS","Hanwha Aerospace","한화에어로"),
            StockReference("329180.KS","HD Hyundai Heavy","HD현대중공업"),
            StockReference("267250.KS","HD Hyundai","HD현대"),
            StockReference("336260.KS","Doosan Fuel Cell","두산퓨얼셀"),
            StockReference("009830.KS","Hanwha Solutions","한화솔루션"),
            StockReference("375500.KS","DL E&C","DL이앤씨"),
            StockReference("014680.KS","Hansol","한솔"),
            StockReference("004990.KS","Lotte Holdings","롯데지주"),
            StockReference("001740.KS","SK Networks","SK네트웍스"),
            StockReference("034220.KS","LG Display","LG디스플레이"),
            StockReference("010140.KS","Samsung Heavy","삼성중공업"),
            StockReference("009540.KS","HD Korea Ship","HD한국조선"),
            StockReference("042700.KS","Hanmi Pharm","한미약품"),
            StockReference("000990.KS","DB Hitek","DB하이텍"),
            StockReference("071050.KS","Korea Investment","한국금융지주"),
            StockReference("006360.KS","GS Engineering","GS건설"),
            StockReference("007070.KS","GS Retail","GS리테일"),
            StockReference("078930.KS","GS","GS"),
            StockReference("138040.KS","Meritz Financial","메리츠금융"),
            StockReference("139480.KS","Ecopro Materials","에코프로머티"),
            StockReference("011780.KS","Kumho Petro","금호석유"),
            StockReference("005070.KS","Cosmo","코스모"),
            StockReference("035250.KS","Kangwon Land","강원랜드"),
            StockReference("020560.KS","Asiana","아시아나항공"),
            StockReference("034830.KS","Korean Re","코리안리"),
            StockReference("001570.KS","Kumho Tire","금호타이어"),
            StockReference("005420.KS","Cosmo AM&T","코스모신소재"),
            StockReference("014830.KS","Yulchon","율촌화학"),
            StockReference("003850.KS","Boryung","보령"),
            StockReference("069620.KS","Daewoo Engineering","대우건설"),
            StockReference("023530.KS","Lotte Shopping","롯데쇼핑")
        ),

        MarketCategory.KOSDAQ to listOf(

            StockReference("247540.KQ","EcoPro BM","에코프로비엠"),
            StockReference("086520.KQ","ECOPRO","에코프로"),
            StockReference("196170.KQ","Alteogen","알테오젠"),
            StockReference("028300.KQ","HLB","HLB"),
            StockReference("066970.KQ","L&F","엘앤에프"),
            StockReference("293490.KQ","Kakao Games","카카오게임즈"),
            StockReference("263750.KQ","Pearl Abyss","펄어비스"),
            StockReference("095660.KQ","NEOWIZ","네오위즈"),
            StockReference("214450.KQ","PharmaResearch","파마리서치"),
            StockReference("214150.KQ","Classys","클래시스"),
            StockReference("145020.KQ","Hugel","휴젤"),
            StockReference("091970.KQ","Nexon Games","넥슨게임즈"),
            StockReference("039030.KQ","EO Technics","이오테크닉스"),
            StockReference("112040.KQ","Wemade","위메이드"),
            StockReference("067310.KQ","Hana Micron","하나마이크론"),
            StockReference("240810.KQ","Wonik IPS","원익IPS"),
            StockReference("357780.KQ","Solus","솔루스첨단소재"),
            StockReference("348370.KQ","Enchem","엔켐"),
            StockReference("058470.KQ","Leeno","리노공업"),
            StockReference("078600.KQ","Daejoo","대주전자재료"),
            StockReference("036830.KQ","SolarEdge","솔브레인"),
            StockReference("078130.KQ","Kukdo","국도화학"),
            StockReference("101490.KQ","AceTech","에이스테크"),
            StockReference("041960.KQ","Korea Circuit","코리아써키트"),
            StockReference("222080.KQ","CosmaxNBT","코스맥스엔비티"),
            StockReference("060720.KQ","KH Vatec","KH바텍"),
            StockReference("272290.KQ","Ecopro HN","에코프로HN"),
            StockReference("214370.KQ","Caregen","케어젠"),
            StockReference("183300.KQ","Korean Refract","코리아에프티"),
            StockReference("096530.KQ","SEEGENE","씨젠"),
            StockReference("033640.KQ","NEPES","네패스"),
            StockReference("032190.KQ","Daeduck","대덕"),
            StockReference("122870.KQ","YG PLUS","YG PLUS"),
            StockReference("046890.KQ","Seegene","씨젠"),
            StockReference("084370.KQ","Eugene Tech","유진테크"),
            StockReference("090460.KQ","BioNiA","비엔나"),
            StockReference("041510.KQ","SM","SM엔터"),
            StockReference("035760.KQ","CJ ENM","CJ ENM"),
            StockReference("253450.KQ","ST Pharm","에스티팜"),
            StockReference("064550.KQ","BioSmart","바이오스마트"),
            StockReference("095700.KQ","Jusung","주성엔지니어링"),
            StockReference("052400.KQ","Kukil","국일제지"),
            StockReference("217270.KQ","Netmarble","넷마블"),
            StockReference("079550.KQ","LIG Nex1","LIG넥스원"),
            StockReference("222800.KQ","Simtec","심텍"),
            StockReference("101160.KQ","Worldex","월덱스"),
            StockReference("035900.KQ","JYP","JYP엔터"),
            StockReference("041020.KQ","Polaris","폴라리스"),
            StockReference("272210.KQ","Hansol Chem","한솔케미칼")
        ),

         MarketCategory.NASDAQ to listOf(
             StockReference("NVDA","NVIDIA","엔비디아"),
            StockReference("AAPL","Apple","애플"),
            StockReference("MSFT","Microsoft","마이크로소프트"),
            StockReference("GOOGL","Alphabet","구글"),
            StockReference("AMZN","Amazon","아마존"),
            StockReference("META","Meta Platforms","메타"),
            StockReference("TSLA","Tesla","테슬라"),
            StockReference("AVGO","Broadcom","브로드컴"),
            StockReference("COST","Costco","코스트코"),
            StockReference("NFLX","Netflix","넷플릭스"),

            StockReference("AMD","AMD","AMD"),
            StockReference("ADBE","Adobe","어도비"),
            StockReference("INTU","Intuit","인튜이트"),
            StockReference("ISRG","Intuitive Surgical","인튜이티브"),
            StockReference("BKNG","Booking","부킹"),
            StockReference("PEP","PepsiCo","펩시"),
            StockReference("CSCO","Cisco","시스코"),
            StockReference("TMUS","T-Mobile","티모바일"),
            StockReference("ASML","ASML","ASML"),
            StockReference("TXN","Texas Instruments","텍사스인스트루먼트"),

            StockReference("QCOM","Qualcomm","퀄컴"),
            StockReference("AMAT","Applied Materials","어플라이드"),
            StockReference("INTC","Intel","인텔"),
            StockReference("MU","Micron","마이크론"),
            StockReference("LRCX","Lam Research","램리서치"),
            StockReference("KLAC","KLA","KLA"),
            StockReference("PANW","Palo Alto","팔로알토"),
            StockReference("SNPS","Synopsys","시놉시스"),
            StockReference("CDNS","Cadence","케이던스"),
            StockReference("MRVL","Marvell","마벨"),

            StockReference("ORLY","OReilly","오라일리"),
            StockReference("REGN","Regeneron","리제네론"),
            StockReference("VRTX","Vertex","버텍스"),
            StockReference("BIIB","Biogen","바이오젠"),
            StockReference("GILD","Gilead","길리어드"),
            StockReference("ADP","ADP","ADP"),
            StockReference("PAYX","Paychex","페이첵스"),
            StockReference("MAR","Marriott","메리어트"),
            StockReference("ROST","Ross","로스"),
            StockReference("MNST","Monster","몬스터"),

            StockReference("CTAS","Cintas","신타스"),
            StockReference("PCAR","PACCAR","파카"),
            StockReference("IDXX","Idexx","아이덱스"),
            StockReference("FAST","Fastenal","패스널"),
            StockReference("ODFL","Old Dominion","ODFL"),
            StockReference("KDP","Keurig Dr Pepper","KDP"),
            StockReference("EA","Electronic Arts","EA"),
            StockReference("TTWO","TakeTwo","테이크투"),
            StockReference("WBD","Warner Bros","워너"),
            StockReference("ZS","Zscaler","지스케일러")
        ),
        MarketCategory.DOW to listOf(

            StockReference("AAPL","Apple","애플"),
            StockReference("MSFT","Microsoft","마이크로소프트"),
            StockReference("AMZN","Amazon","아마존"),
            StockReference("V","Visa","비자"),
            StockReference("WMT","Walmart","월마트"),
            StockReference("JPM","JPMorgan","JP모건"),
            StockReference("UNH","UnitedHealth","유나이티드헬스"),
            StockReference("HD","Home Depot","홈디포"),
            StockReference("PG","Procter & Gamble","P&G"),
            StockReference("CRM","Salesforce","세일즈포스"),

            StockReference("GS","Goldman Sachs","골드만삭스"),
            StockReference("MCD","McDonalds","맥도날드"),
            StockReference("CAT","Caterpillar","캐터필러"),
            StockReference("IBM","IBM","IBM"),
            StockReference("AXP","American Express","아멕스"),
            StockReference("JNJ","Johnson & Johnson","존슨앤존슨"),
            StockReference("HON","Honeywell","허니웰"),
            StockReference("TRV","Travelers","트래블러스"),
            StockReference("CVX","Chevron","쉐브론"),
            StockReference("DIS","Disney","디즈니"),

            StockReference("KO","Coca Cola","코카콜라"),
            StockReference("NKE","Nike","나이키"),
            StockReference("MRK","Merck","머크"),
            StockReference("MMM","3M","3M"),
            StockReference("BA","Boeing","보잉"),
            StockReference("DOW","Dow","다우"),
            StockReference("WBA","Walgreens","월그린"),
            StockReference("CSCO","Cisco","시스코"),
            StockReference("INTC","Intel","인텔"),
            StockReference("VZ","Verizon","버라이즌"),

            StockReference("PFE","Pfizer","화이자"),
            StockReference("RTX","RTX","RTX"),
            StockReference("XOM","Exxon","엑슨"),
            StockReference("CVS","CVS","CVS"),
            StockReference("GE","GE","GE"),
            StockReference("GM","GM","GM"),
            StockReference("F","Ford","포드"),
            StockReference("T","AT&T","AT&T"),
            StockReference("UPS","UPS","UPS"),
            StockReference("FDX","FedEx","페덱스"),

            StockReference("BK","Bank of NY","BNY"),
            StockReference("BLK","BlackRock","블랙록"),
            StockReference("SCHW","Charles Schwab","찰스슈왑"),
            StockReference("SPGI","S&P Global","S&P"),
            StockReference("ICE","Intercontinental","ICE"),
            StockReference("C","Citigroup","씨티"),
            StockReference("USB","US Bancorp","US뱅크"),
            StockReference("PNC","PNC","PNC"),
            StockReference("TGT","Target","타겟"),
            StockReference("LOW","Lowes","로우스")
        ),

        MarketCategory.CRYPTO_TOP to listOf(

            StockReference("BTC-USD","Bitcoin","비트코인"),
            StockReference("ETH-USD","Ethereum","이더리움"),
            StockReference("BNB-USD","BNB","BNB"),
            StockReference("SOL-USD","Solana","솔라나"),
            StockReference("XRP-USD","XRP","리플"),
            StockReference("ADA-USD","Cardano","카르다노"),
            StockReference("DOGE-USD","Dogecoin","도지코인"),
            StockReference("AVAX-USD","Avalanche","아발란체"),
            StockReference("DOT-USD","Polkadot","폴카닷"),
            StockReference("LINK-USD","Chainlink","체인링크"),

            StockReference("MATIC-USD","Polygon","폴리곤"),
            StockReference("ATOM-USD","Cosmos","코스모스"),
            StockReference("LTC-USD","Litecoin","라이트코인"),
            StockReference("BCH-USD","Bitcoin Cash","비트코인캐시"),
            StockReference("UNI-USD","Uniswap","유니스왑"),
            StockReference("AAVE-USD","Aave","아베"),
            StockReference("NEAR-USD","NEAR","니어"),
            StockReference("ICP-USD","Internet Computer","ICP"),
            StockReference("FIL-USD","Filecoin","파일코인"),
            StockReference("APT-USD","Aptos","앱토스")
        ),
        MarketCategory.OIL to listOf(

            StockReference("CL=F","WTI Crude Oil","WTI 원유"),
            StockReference("BZ=F","Brent Oil","브렌트유"),
            StockReference("NG=F","Natural Gas","천연가스"),
            StockReference("RB=F","Gasoline","가솔린"),
            StockReference("HO=F","Heating Oil","난방유")
        ),

        MarketCategory.METAL to listOf(

            StockReference("GC=F","Gold","금"),
            StockReference("SI=F","Silver","은"),
            StockReference("HG=F","Copper","구리"),
            StockReference("PL=F","Platinum","백금"),
            StockReference("PA=F","Palladium","팔라듐")
        ),

        MarketCategory.AGRI to listOf(

            StockReference("ZC=F","Corn","옥수수"),
            StockReference("ZW=F","Wheat","밀"),
            StockReference("ZS=F","Soybean","대두"),
            StockReference("KC=F","Coffee","커피"),
            StockReference("CC=F","Cocoa","코코아")
        )
    )
}