# Generated by Django 6.0.3 on 2026-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
