# Generated by Django 6.0.3 on 2026-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_category_exam_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='choice_images/'),
        ),
    ]
